Edit profile
cmeue/cmeue pull request #10
Opened 2016-11-04 13:26 UTC by ishancoder

Hi, Guys i've created Edit Profile Page please review it and let me know if any changes are to be made.

2016-11-05 18:36 UTC, razat249 commented
@ishancoder Also add the UI screenshot of your page.

2016-12-30 15:35 UTC, razat249 requested changes
Everything seems nice and working perfectly. Just need some research and changes. nice work :+1:

2016-12-30 15:35 UTC, razat249 commented on .eslintrc.json
> +        ],
great :+1:

2016-12-30 15:35 UTC, razat249 commented on src/components/common/Pill/Pill.jsx
> +            <div className="pill-component">{this.props.children} <span className={this.props.cross === "true" ? "glyphicon glyphicon-remove" : ""}></span></div>
Split in multiple lines

2016-12-30 15:35 UTC, razat249 commented on src/components/common/DropDown/DropDown.jsx
> +        for (let i = 0; i < this.props.contents.length; i++) {
Research if this is the right way to use for loop or any other functionality code(I mean inside the render function). There are other ways like constructor and react Component life cycle etc. Learn about them and also learn when to use what.

2016-12-30 15:35 UTC, razat249 commented on src/components/common/SkillArea/SkillArea.jsx
> +        let skillArray = this.props.skillSet;
Also confirm it here if this is right and in every component do the same.

2016-12-31 05:27 UTC, ishancoder commented on .eslintrc.json
> +        ],
Thanks

2016-12-31 05:27 UTC, ishancoder commented on src/components/common/Pill/Pill.jsx
> +            <div className="pill-component">{this.props.children} <span className={this.props.cross === "true" ? "glyphicon glyphicon-remove" : ""}></span></div>
Done!

2016-12-31 05:28 UTC, ishancoder commented on src/components/common/DropDown/DropDown.jsx
> +        for (let i = 0; i < this.props.contents.length; i++) {
as thinkster.io this the current best practice however I've changed this for loop to JavaScripts Map function.

2016-12-31 05:30 UTC, ishancoder commented on src/components/common/SkillArea/SkillArea.jsx
> +        let skillArray = this.props.skillSet;
Same here!

2016-12-31 05:31 UTC, ishancoder commented
Hi, Reviewer I've made appropriate changes as requested. Thanks for reviewing.

2016-12-31 08:03 UTC, razat249 approved these changes
Nicely done

2016-12-31 08:03 UTC, merged